LIBDIRS= -framework GLUT -framework OpenGL
LDLIBS = -lobjc -lm -lpng -lz

CPPFLAGS= -I/opt/local/include
LDFLAGS= $(CPPFLAGS) $(LIBDIRS)

TARGETS = 

SRCS = 

OBJS = $(SRCS:.cpp=.o)

CXX = g++

default: $(TARGETS)
